### ISSUE TITLE
Random Resize and Cropping

### ISSUE THREAD

**Issue by haruishi43** [YunzeMan/DualCross#1]
Thank you for open-sourcing your work.

I noticed in your paper you said that you used "random cropping".
However, in the code, [random cropping will only trigger](https://github.com/YunzeMan/DualCross/blob/ca7e3b2f48653fe8007d0bbb6149e6e1237824af/src/data.py#L124) if `rand_resize=True` and in the readme, the script argument has `--rand_resize=False` for both training the lidar teacher and student.
Did you accidentally write that you used "random cropping," or did you turn on `--rand_resize`?
I haven't run your code, but I noticed while experimenting with another project that random resizing and random cropping show lower IoU (around 1~2%) compared to consistent resizing. Did you also notice this during your experimentation?

**Comment by YunzeMan** [comment]
Thanks for your comment! You are correct that `--rand_resize` was turned on for our best performed model. What I noticed was that random resizing combined with cropping aids in domain shifts involving changes in camera settings, such as the intrinsic matrix. However, when domain shifts are limited to variations in weather or lighting within the same dataset, the benefits of random cropping are less pronounced. Regarding the 2% IoU drop you mentioned, I don't remember observing it in our results, but exploring different configurations to investigate this aspect could be valuable

**Comment by haruishi43** [comment]
Thank you for your reply. Good to know that `--rand_resize` is being used in the paper.

I can see that random resizing + cropping can aid in domain shifts involving changes in camera settings. By this do you mean it helped in your experiment with dataset-to-dataset domain gaps?

**Comment by YunzeMan** [comment]
Yes that's correct.
